name: Build AAB

on:
  #  workflow_dispatch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Prepare Keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'keystore/keystore.jks'
          encodedString: ${{secrets.BASE64_KEYSTORE}}

      - name: Prepare Keystore variables
        run: |
          echo "keystore_path=${GITHUB_WORKSPACE}/keystore/keystore.jks"
          echo "keystore_password=${KEYSTORE_PASSWORD}"
          echo "keystore_key_alias=${KEYSTORE_KEY_ALIAS}"
          echo "keystore_key_password=${KEYSTORE_KEY_PASSWORD}"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build AAB with Gradle
        run: ./gradlew :app:bundleRelease
        with:
          name: AAB
          path: app/build/outputs/
