name: Build Compatible Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Prepare Keystore variables
        run: |
          echo "keystore_path=foo" &>> local.properties
          echo "keystore_password=foo" &>> local.properties
          echo "keystore_key_alias=foo" &>> local.properties
          echo "keystore_key_password=foo" &>> local.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew buildDebug
